language: node_js

node_js:
  - stable
  - lts/boron
  - lts/argon

before_install: npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - npm install --global nyc coveralls
  - nyc report --reporter=text-lcov | coveralls
